version: '3.8'

services:
  vue-app:
    image: node:20
    container_name: vue_app
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    command: sh -c "npm install && npm run serve"
  
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "70:80"
    volumes:
      - ./dist:/usr/share/nginx/html
    depends_on:
      - vue-app

volumes:
  dist:
